import type {
  AuditEvent,
  BindingTimelineEvent,
  GroupAssignment,
  GroupBinding,
  GroupTemplate,
  KnowledgeDoc,
  KnowledgeDocVersion,
  MediaAsset,
  MessageDecisionRecord,
  MessageRecord,
  MessageVersion,
  PromptAsset,
  RuntimeDebugStatus,
  StaffUser,
  TemplateVersion,
  ToolCatalogItem,
  ToolInvocationRecord,
  TraceDetail,
} from "@/lib/api-client/types";

export const templates: GroupTemplate[] = [
  {
    id: "tpl-support",
    key: "support-default",
    displayName: "Support Assistant",
    description: "Default support operations template with moderated tool set.",
    publishedVersionId: "tplv-support-3",
    updatedAt: "2026-04-18T10:15:00Z",
  },
  {
    id: "tpl-vip",
    key: "vip-concierge",
    displayName: "VIP Concierge",
    description: "Low-latency hot runtime template for premium groups.",
    publishedVersionId: "tplv-vip-2",
    updatedAt: "2026-04-18T09:48:00Z",
  },
];

export const templateVersions: TemplateVersion[] = [
  {
    id: "tplv-support-1",
    templateId: "tpl-support",
    versionNo: 1,
    status: "archived",
    modelChain: ["gpt-5.5"],
    reasoningEffort: "medium",
    toolProfile: "read-only",
    knowledgeProfile: "common: *, group: *",
    egressPolicy: "restricted",
    updatedAt: "2026-04-16T10:00:00Z",
    updatedBy: "admin@kuuna.ai",
  },
  {
    id: "tplv-support-2",
    templateId: "tpl-support",
    versionNo: 2,
    status: "ready",
    modelChain: ["gpt-5.5"],
    reasoningEffort: "medium",
    toolProfile: "balanced",
    knowledgeProfile: "common: *, group: *",
    egressPolicy: "restricted",
    updatedAt: "2026-04-17T15:10:00Z",
    updatedBy: "operator@kuuna.ai",
  },
  {
    id: "tplv-support-3",
    templateId: "tpl-support",
    versionNo: 3,
    status: "published",
    modelChain: ["gpt-5.5"],
    reasoningEffort: "medium",
    toolProfile: "balanced",
    knowledgeProfile: "common: *, group: *",
    egressPolicy: "restricted",
    updatedAt: "2026-04-18T10:15:00Z",
    updatedBy: "admin@kuuna.ai",
  },
  {
    id: "tplv-vip-1",
    templateId: "tpl-vip",
    versionNo: 1,
    status: "archived",
    modelChain: ["gpt-5.5"],
    reasoningEffort: "medium",
    toolProfile: "vip-safe",
    knowledgeProfile: "common: *, group: *",
    egressPolicy: "strict",
    updatedAt: "2026-04-17T12:10:00Z",
    updatedBy: "owner@kuuna.ai",
  },
  {
    id: "tplv-vip-2",
    templateId: "tpl-vip",
    versionNo: 2,
    status: "published",
    modelChain: ["gpt-5.5"],
    reasoningEffort: "medium",
    toolProfile: "vip-safe",
    knowledgeProfile: "common: *, group: *",
    egressPolicy: "strict",
    updatedAt: "2026-04-18T09:48:00Z",
    updatedBy: "owner@kuuna.ai",
  },
];

export const toolCatalog: ToolCatalogItem[] = [
  {
    id: "tool-echo",
    toolKey: "echo",
    displayName: "Echo",
    description: "Returns the provided input text unchanged.",
    riskClass: "read",
    category: "utility",
    isEnabled: true,
    updatedAt: "2026-04-18T10:15:00Z",
  },
  {
    id: "tool-uppercase",
    toolKey: "uppercase",
    displayName: "Uppercase",
    description: "Converts text to uppercase deterministically.",
    riskClass: "read",
    category: "utility",
    isEnabled: true,
    updatedAt: "2026-04-18T10:16:00Z",
  },
  {
    id: "tool-knowledge-search",
    toolKey: "knowledge_search",
    displayName: "Knowledge Search",
    description: "Searches group/common knowledge for relevant passages.",
    riskClass: "read",
    category: "knowledge",
    isEnabled: true,
    updatedAt: "2026-04-18T10:18:00Z",
  },
  {
    id: "tool-send-whatsapp",
    toolKey: "send_whatsapp",
    displayName: "Send WhatsApp",
    description: "Sends outbound messages via gateway with idempotency.",
    riskClass: "write",
    category: "communication",
    isEnabled: true,
    updatedAt: "2026-04-18T10:20:00Z",
  },
];

export const bindings: GroupBinding[] = [
  {
    id: "bind-fo-1",
    providerGroupId: "grp-family-office",
    groupTitle: "Family Office Clients",
    templateVersionId: "tplv-support-3",
    status: "active",
    runtimeMode: "on-demand",
    updatedAt: "2026-04-18T11:20:00Z",
  },
  {
    id: "bind-vip-1",
    providerGroupId: "grp-vip-founders",
    groupTitle: "VIP Founders",
    templateVersionId: "tplv-vip-2",
    status: "active",
    runtimeMode: "hot",
    updatedAt: "2026-04-18T10:20:00Z",
  },
  {
    id: "bind-ops-1",
    providerGroupId: "grp-internal-ops",
    groupTitle: "Internal Ops",
    templateVersionId: "tplv-support-2",
    status: "provisioning",
    runtimeMode: "on-demand",
    updatedAt: "2026-04-18T11:55:00Z",
  },
];

export const bindingTimeline: BindingTimelineEvent[] = [
  {
    id: "evt-1",
    bindingId: "bind-ops-1",
    status: "draft",
    label: "Binding created",
    occurredAt: "2026-04-18T11:49:00Z",
  },
  {
    id: "evt-2",
    bindingId: "bind-ops-1",
    status: "provisioning",
    label: "Runtime provisioning started",
    occurredAt: "2026-04-18T11:50:00Z",
  },
  {
    id: "evt-3",
    bindingId: "bind-ops-1",
    status: "processing",
    label: "Health check in progress",
    occurredAt: "2026-04-18T11:52:00Z",
    details: "Container booted; waiting for warm prompt load",
  },
  {
    id: "evt-4",
    bindingId: "bind-vip-1",
    status: "active",
    label: "Activated",
    occurredAt: "2026-04-18T10:20:00Z",
    details: "Disclosure message sent successfully",
  },
];

export const promptAssets: PromptAsset[] = [
  {
    id: "pa-system-fo-4",
    templateId: "tpl-support",
    templateName: "Support Assistant",
    templateVersionId: "tplv-support-3",
    instanceId: "bind-fo-1",
    instanceName: "Family Office Clients",
    type: "system",
    title: "System Prompt",
    status: "draft",
    versionNo: 4,
    updatedAt: "2026-04-18T10:40:00Z",
    updatedBy: "operator@kuuna.ai",
  },
  {
    id: "pa-user-fo-2",
    templateId: "tpl-support",
    templateName: "Support Assistant",
    templateVersionId: "tplv-support-3",
    instanceId: "bind-fo-1",
    instanceName: "Family Office Clients",
    type: "user",
    title: "USER.md",
    status: "published",
    versionNo: 2,
    updatedAt: "2026-04-18T08:12:00Z",
    updatedBy: "admin@kuuna.ai",
  },
  {
    id: "pa-system-vip-3",
    templateId: "tpl-vip",
    templateName: "VIP Concierge",
    templateVersionId: "tplv-vip-2",
    instanceId: "bind-vip-1",
    instanceName: "VIP Founders",
    type: "system",
    title: "System Prompt",
    status: "published",
    versionNo: 3,
    updatedAt: "2026-04-18T09:45:00Z",
    updatedBy: "owner@kuuna.ai",
  },
];

export const knowledgeDocs: KnowledgeDoc[] = [
  {
    id: "k-common-1",
    docKey: "global-escalation-policy",
    scope: "common",
    title: "Global Escalation Policy",
    status: "published",
    updatedAt: "2026-04-18T08:10:00Z",
    updatedBy: "admin@kuuna.ai",
    chunkCount: 12,
  },
  {
    id: "k-common-2",
    docKey: "faq-incident-response",
    scope: "common",
    title: "FAQ: Incident Response",
    status: "ready",
    updatedAt: "2026-04-18T11:15:00Z",
    updatedBy: "operator@kuuna.ai",
    chunkCount: 20,
  },
  {
    id: "k-group-fo-1",
    docKey: "family-office-agreement-notes",
    scope: "group",
    providerGroupId: "grp-family-office",
    title: "Family Office Agreement Notes",
    status: "processing",
    updatedAt: "2026-04-18T11:42:00Z",
    updatedBy: "operator@kuuna.ai",
    chunkCount: 7,
  },
  {
    id: "k-group-vip-1",
    docKey: "vip-contact-preferences",
    scope: "group",
    providerGroupId: "grp-vip-founders",
    title: "VIP Contact Preferences",
    status: "published",
    updatedAt: "2026-04-18T09:55:00Z",
    updatedBy: "owner@kuuna.ai",
    chunkCount: 9,
  },
];

export const knowledgeVersions: KnowledgeDocVersion[] = [
  {
    id: "kcv-1",
    scope: "common",
    docRefId: "k-common-1",
    versionNo: 1,
    status: "archived",
    contentMarkdown: "# Global Escalation Policy v1\n\nLegacy policy details.",
    createdAt: "2026-04-17T08:00:00Z",
    updatedAt: "2026-04-17T08:00:00Z",
    updatedBy: "admin@kuuna.ai",
  },
  {
    id: "kcv-2",
    scope: "common",
    docRefId: "k-common-1",
    versionNo: 2,
    status: "published",
    contentMarkdown: "# Global Escalation Policy v2\n\nCurrent policy details.",
    createdAt: "2026-04-18T08:10:00Z",
    updatedAt: "2026-04-18T08:10:00Z",
    updatedBy: "admin@kuuna.ai",
  },
  {
    id: "kcv-3",
    scope: "common",
    docRefId: "k-common-2",
    versionNo: 1,
    status: "ready",
    contentMarkdown: "# FAQ: Incident Response\n\nPrepared and indexed.",
    createdAt: "2026-04-18T11:15:00Z",
    updatedAt: "2026-04-18T11:15:00Z",
    updatedBy: "operator@kuuna.ai",
  },
  {
    id: "kgv-1",
    scope: "group",
    docRefId: "k-group-vip-1",
    versionNo: 1,
    status: "published",
    contentMarkdown: "# VIP Contact Preferences\n\nUse short responses.",
    createdAt: "2026-04-18T09:55:00Z",
    updatedAt: "2026-04-18T09:55:00Z",
    updatedBy: "owner@kuuna.ai",
  },
];

export const messages: MessageRecord[] = [
  {
    id: "msg-001",
    providerGroupId: "grp-family-office",
    sender: "+43 664 111222",
    preview: "@kuuna Can you summarize the latest policy update?",
    hasMedia: false,
    isDeleted: false,
    latestVersionNo: 1,
    createdAt: "2026-04-18T10:01:00Z",
  },
  {
    id: "msg-002",
    providerGroupId: "grp-family-office",
    sender: "+43 664 222333",
    preview: "Uploading signed document now",
    hasMedia: true,
    isDeleted: false,
    latestVersionNo: 2,
    createdAt: "2026-04-18T10:15:00Z",
  },
  {
    id: "msg-003",
    providerGroupId: "grp-vip-founders",
    sender: "+43 664 555999",
    preview: "Please ignore my previous note",
    hasMedia: false,
    isDeleted: true,
    latestVersionNo: 2,
    createdAt: "2026-04-18T10:22:00Z",
  },
];

export const messageVersions: MessageVersion[] = [
  {
    id: "mv-001",
    messageId: "msg-001",
    versionNo: 1,
    eventType: "created",
    text: "@kuuna Can you summarize the latest policy update?",
    occurredAt: "2026-04-18T10:01:00Z",
  },
  {
    id: "mv-002",
    messageId: "msg-002",
    versionNo: 1,
    eventType: "created",
    text: "Uploading signed doc",
    occurredAt: "2026-04-18T10:15:00Z",
  },
  {
    id: "mv-003",
    messageId: "msg-002",
    versionNo: 2,
    eventType: "edited",
    text: "Uploading signed document now",
    occurredAt: "2026-04-18T10:15:32Z",
  },
  {
    id: "mv-004",
    messageId: "msg-003",
    versionNo: 1,
    eventType: "created",
    text: "Please ignore my previous note",
    occurredAt: "2026-04-18T10:22:00Z",
  },
  {
    id: "mv-005",
    messageId: "msg-003",
    versionNo: 2,
    eventType: "deleted",
    text: "",
    occurredAt: "2026-04-18T10:24:00Z",
  },
];

export const mediaAssets: MediaAsset[] = [
  {
    id: "ma-1",
    messageId: "msg-002",
    kind: "file",
    filename: "signed-agreement.pdf",
    status: "ready",
    transcript: "Extracted 8 pages of text. Key clause includes 14-day cancellation window.",
  },
  {
    id: "ma-2",
    messageId: "msg-002",
    kind: "image",
    filename: "invoice-photo.jpg",
    status: "ready",
    previewUrl: "https://placehold.co/900x600/png?text=WhatsApp+Image",
  },
  {
    id: "ma-3",
    messageId: "msg-003",
    kind: "audio",
    filename: "voice-note-0418.m4a",
    status: "queued",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "audit-1",
    eventType: "template.publish",
    actor: "admin@kuuna.ai",
    entityType: "template_version",
    entityId: "tplv-support-3",
    traceId: "trace-1744971220",
    createdAt: "2026-04-18T10:15:30Z",
    metadata: "Published from draft v3",
  },
  {
    id: "audit-2",
    eventType: "binding.activate",
    actor: "owner@kuuna.ai",
    entityType: "group_binding",
    entityId: "bind-vip-1",
    traceId: "trace-1744971401",
    createdAt: "2026-04-18T10:20:05Z",
    metadata: "Runtime hot mode active",
  },
  {
    id: "audit-3",
    eventType: "knowledge.index",
    actor: "system",
    entityType: "knowledge_version",
    entityId: "k-group-fo-1",
    traceId: "trace-1744978200",
    createdAt: "2026-04-18T11:42:10Z",
    metadata: "Indexing in progress",
  },
];

export const traceDetails: TraceDetail[] = [
  {
    traceId: "trace-1744971220",
    providerGroupId: "grp-family-office",
    inboundEventId: "in-88211",
    retrievalRefs: ["k-common-1#3", "k-group-fo-1#1", "msg-001#v1"],
    modelPath: ["gpt-5.5"],
    outboundIntentId: "out-7711",
  },
  {
    traceId: "trace-1744971401",
    providerGroupId: "grp-vip-founders",
    inboundEventId: "in-88231",
    retrievalRefs: ["k-group-vip-1#2", "k-common-1#6"],
    modelPath: ["gpt-5.5"],
    outboundIntentId: "out-7720",
  },
  {
    traceId: "trace-1744978200",
    providerGroupId: "grp-family-office",
    inboundEventId: "index-job-912",
    retrievalRefs: ["k-group-fo-1#all"],
    modelPath: ["n/a"],
    outboundIntentId: "n/a",
  },
];

export const messageDecisions: MessageDecisionRecord[] = [
  {
    id: "decision-1",
    messageId: "msg-001",
    providerGroupId: "grp-family-office",
    groupTitle: "Family Office",
    decisionType: "passive_analysis",
    reason: "message_received",
    shouldExecute: false,
    payloadSummary: '{"created_todo_count":1,"allowed_tools":["todo_create"]}',
    createdAt: "2026-04-18T10:18:44Z",
  },
  {
    id: "decision-2",
    messageId: "msg-002",
    providerGroupId: "grp-vip-founders",
    groupTitle: "VIP Founders",
    decisionType: "agent_mention",
    reason: "direct_mention",
    shouldExecute: true,
    payloadSummary: '{"trigger_type":"mention","model_path":["gpt-5.5"]}',
    createdAt: "2026-04-18T10:21:05Z",
  },
];

export const toolInvocations: ToolInvocationRecord[] = [
  {
    id: "tool-invocation-1",
    agentRunId: "run-001",
    messageId: "msg-001",
    providerGroupId: "grp-family-office",
    groupTitle: "Family Office",
    toolName: "todo_create",
    ok: true,
    stdoutPreview: '{"title":"Collect invoice screenshots"}',
    timedOut: false,
    durationMs: 42,
    detailsSummary: '{"operation":"create","priority":"high"}',
    createdAt: "2026-04-18T10:18:46Z",
  },
  {
    id: "tool-invocation-2",
    agentRunId: "run-002",
    messageId: "msg-002",
    providerGroupId: "grp-vip-founders",
    groupTitle: "VIP Founders",
    toolName: "knowledge_search",
    ok: true,
    stdoutPreview: '{"hits":[{"source_scope":"group"}]}',
    timedOut: false,
    durationMs: 18,
    detailsSummary: '{"query":"financing conditions","hit_count":1}',
    createdAt: "2026-04-18T10:21:07Z",
  },
];

export const runtimeDebugStatus: RuntimeDebugStatus = {
  runtimeHealth: "ok",
  runtimeUrl: "http://runtime-agent:8100",
  openaiConfigured: true,
  openaiBaseUrl: "https://api.openai.com/v1",
  openaiTimeoutSeconds: "30",
  defaultModel: "gpt-5.5",
  reasoningEffort: "medium",
  lastModelPath: ["gpt-5.5"],
  lastModelUsed: "gpt-5.5",
  lastOutboundIntentId: "out-7720",
  lastOutboundAt: "2026-04-18T10:20:05Z",
};

export const users: StaffUser[] = [
  {
    id: "u-owner",
    email: "owner@kuuna.ai",
    displayName: "Owner",
    role: "owner",
    active: true,
  },
  {
    id: "u-admin",
    email: "admin@kuuna.ai",
    displayName: "Platform Admin",
    role: "admin",
    active: true,
  },
  {
    id: "u-ops-1",
    email: "operator@kuuna.ai",
    displayName: "Operations",
    role: "operator",
    active: true,
  },
  {
    id: "u-view",
    email: "viewer@kuuna.ai",
    displayName: "Read Only",
    role: "viewer",
    active: true,
  },
];

export const groupAssignments: GroupAssignment[] = [
  {
    id: "ga-1",
    userId: "u-ops-1",
    user: "operator@kuuna.ai",
    providerGroupId: "grp-family-office",
    groupTitle: "Family Office Clients",
  },
  {
    id: "ga-2",
    userId: "u-ops-1",
    user: "operator@kuuna.ai",
    providerGroupId: "grp-vip-founders",
    groupTitle: "VIP Founders",
  },
  {
    id: "ga-3",
    userId: "u-view",
    user: "viewer@kuuna.ai",
    providerGroupId: "grp-family-office",
    groupTitle: "Family Office Clients",
  },
];
